package model;
// Generated 07/08/2016 15:51:08 by Hibernate Tools 4.3.1



/**
 * ParcelasPagar generated by hbm2java
 */
public class ParcelasPagar  implements java.io.Serializable {


     private Integer idParcela;
     private int contaPagar;
     private Integer numeroparcela;
     private String datavencimento;
     private String datapagamento;
     private Double valor;
     private boolean status;

    public ParcelasPagar() {
    }

	
    public ParcelasPagar(int contaPagar, Integer numeroparcela, String datavencimento, String datapagamento, Double valor, boolean status) {
       this.contaPagar = contaPagar;
       this.numeroparcela = numeroparcela;
       this.datavencimento = datavencimento;
       this.datapagamento = datapagamento;
       this.valor = valor;
       this.status = status;
    }
   
    public Integer getIdParcela() {
        return this.idParcela;
    }
    
    public void setIdParcela(Integer idParcela) {
        this.idParcela = idParcela;
    }
    public int getContaPagar() {
        return this.contaPagar;
    }
    
    public void setContaPagar(int contaPagar) {
        this.contaPagar = contaPagar;
    }
    public Integer getNumeroparcela() {
        return this.numeroparcela;
    }
    
    public void setNumeroparcela(Integer numeroparcela) {
        this.numeroparcela = numeroparcela;
    }
    public String getDatavencimento() {
        return this.datavencimento;
    }
    
    public void setDatavencimento(String datavencimento) {
        this.datavencimento = datavencimento;
    }
    public String getDatapagamento() {
        return this.datapagamento;
    }
    
    public void setDatapagamento(String datapagamento) {
        this.datapagamento = datapagamento;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


