package model;
// Generated 10/08/2016 17:23:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer idPedido;
     private Pessoa pessoaByIdRepresentante;
     private Pessoa pessoaByIdPessoa;
     private Double fator;
     private Double valor;
     private String status;
     private Set itemPedidos = new HashSet(0);
     private Set contaRecebers = new HashSet(0);

    public Pedidos() {
    }

    public Pedidos(Pessoa pessoaByIdRepresentante, Pessoa pessoaByIdPessoa, Double fator, Double valor, String status, Set itemPedidos, Set contaRecebers) {
       this.pessoaByIdRepresentante = pessoaByIdRepresentante;
       this.pessoaByIdPessoa = pessoaByIdPessoa;
       this.fator = fator;
       this.valor = valor;
       this.status = status;
       this.itemPedidos = itemPedidos;
       this.contaRecebers = contaRecebers;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Pessoa getPessoaByIdRepresentante() {
        return this.pessoaByIdRepresentante;
    }
    
    public void setPessoaByIdRepresentante(Pessoa pessoaByIdRepresentante) {
        this.pessoaByIdRepresentante = pessoaByIdRepresentante;
    }
    public Pessoa getPessoaByIdPessoa() {
        return this.pessoaByIdPessoa;
    }
    
    public void setPessoaByIdPessoa(Pessoa pessoaByIdPessoa) {
        this.pessoaByIdPessoa = pessoaByIdPessoa;
    }
    public Double getFator() {
        return this.fator;
    }
    
    public void setFator(Double fator) {
        this.fator = fator;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getItemPedidos() {
        return this.itemPedidos;
    }
    
    public void setItemPedidos(Set itemPedidos) {
        this.itemPedidos = itemPedidos;
    }
    public Set getContaRecebers() {
        return this.contaRecebers;
    }
    
    public void setContaRecebers(Set contaRecebers) {
        this.contaRecebers = contaRecebers;
    }




}


