package model;
// Generated 06/08/2016 14:48:22 by Hibernate Tools 4.3.1

import model.Pessoa;




/**
 * PessoaFisica generated by hbm2java
 */
public class PessoaFisica  implements java.io.Serializable {


     private int idPessoaFisica;
     private String nome;
     private String cpf;
     private String rg;
     private String senha;
     private boolean excluido;

    public PessoaFisica() {
    }

	public PessoaFisica(int pessoa) {
        this.idPessoaFisica = pessoa;
    }
    
    public PessoaFisica(int idPessoaFisica, String nome, String cpf, String rg, String senha, boolean excluido) {
       this.idPessoaFisica = idPessoaFisica;
       this.nome = nome;
       this.cpf = cpf;
       this.rg = rg;
       this.senha = senha;
       this.excluido = excluido;
    }

    public boolean isExcluido() {
        return excluido;
    }

    public void setExcluido(boolean excluido) {
        this.excluido = excluido;
    }
    
   
    public int getIdPessoaFisica() {
        return this.idPessoaFisica;
    }
    
    public void setIdPessoaFisica(int idPessoaFisica) {
        this.idPessoaFisica = idPessoaFisica;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


