package model;
// Generated 06/08/2016 14:48:22 by Hibernate Tools 4.3.1

import model.Pessoa;




/**
 * PessoaJuridica generated by hbm2java
 */
public class PessoaJuridica  implements java.io.Serializable {


     private int idPessoaJuridica;
     private int pessoa;
     private String cnpj;
     private String inscricaoestadual;
     private String razaosocial;
     private String nomefantasia;
     private String tipo;
     private boolean excluido;
     
    public PessoaJuridica() {
    }

	
    public PessoaJuridica(int pessoa) {
        this.pessoa = pessoa;
    }
    
    public PessoaJuridica(int idPessoaJuridica, int pessoa, String cnpj, String inscricaoestadual, String razaosocial, String nomefantasia, String tipo, boolean excluido) {
       this.idPessoaJuridica = idPessoaJuridica;
       this.cnpj = cnpj;
       this.pessoa = pessoa;
       this.inscricaoestadual = inscricaoestadual;
       this.razaosocial = razaosocial;
       this.nomefantasia = nomefantasia;
       this.tipo = tipo;
       this.excluido = excluido;
    }
    
   
    public int getIdPessoaJuridica() {
        return this.idPessoaJuridica;
    }
    
    public void setIdPessoaJuridica(int idPessoaJuridica) {
        this.idPessoaJuridica = idPessoaJuridica;
    }
    public int getPessoa() {
        return this.pessoa;
    }

    public boolean isExcluido() {
        return excluido;
    }

    public void setExcluido(boolean excluido) {
        this.excluido = excluido;
    }
    
    
    public void setPessoa(int pessoa) {
        this.pessoa = pessoa;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getInscricaoestadual() {
        return this.inscricaoestadual;
    }
    
    public void setInscricaoestadual(String inscricaoestadual) {
        this.inscricaoestadual = inscricaoestadual;
    }
    public String getRazaosocial() {
        return this.razaosocial;
    }
    
    public void setRazaosocial(String razaosocial) {
        this.razaosocial = razaosocial;
    }
    public String getNomefantasia() {
        return this.nomefantasia;
    }
    
    public void setNomefantasia(String nomefantasia) {
        this.nomefantasia = nomefantasia;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


