/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ContaDAO;
import dao.PessoaDAO;
import javax.swing.JOptionPane;
import model.ContaPagar;
import model.Pessoa;

/**
 *
 * @author viviane
 */
public class NovaContaFrame extends javax.swing.JFrame {

    ContaPagar conta;
    /**
     * Creates new form NovaContaFrame
     */
    public NovaContaFrame() {

        initComponents();
        pagar.setVisible(false);
        cadastrar.setVisible(true);
        editar.setVisible(false);
    }

    public NovaContaFrame(ContaPagar conta) {
        this.conta = conta;
        pagar.setVisible(true);
        cadastrar.setVisible(false);
        editar.setVisible(true);
        id.setText(""+conta.getIdContaPagar());
        vencimento.setText(conta.getVencimento());
        receptor.setText(""+conta.getPessoa());
        valor.setText(""+conta.getValor());
        parcelas.setText(""+conta.getQtdparcelas());
        descricao.setText(conta.getDescricao());
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        receptor = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        parcelas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vencimento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cadastrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pagar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        descricao = new javax.swing.JTextField();
        plasnedoMenuBar = new javax.swing.JMenuBar();
        pessoaMenu = new javax.swing.JMenu();
        produtoMenu = new javax.swing.JMenu();
        pedido = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID*");

        jLabel2.setText("Receptor*");

        jLabel3.setText("Valor*");

        jLabel4.setText("Parcelas*");

        jLabel5.setText("Vencimento*");

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        jLabel6.setText("Descrição");

        pagar.setText("Pagar");
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarActionPerformed(evt);
            }
        });

        editar.setText("Alterar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoActionPerformed(evt);
            }
        });

        pessoaMenu.setText("Pessoa");
        pessoaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pessoaMenuMouseClicked(evt);
            }
        });
        pessoaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaMenuActionPerformed(evt);
            }
        });
        plasnedoMenuBar.add(pessoaMenu);

        produtoMenu.setText("Produto");
        produtoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtoMenuMouseClicked(evt);
            }
        });
        produtoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoMenuActionPerformed(evt);
            }
        });
        plasnedoMenuBar.add(produtoMenu);

        pedido.setText("Pedido");
        pedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedidoMouseClicked(evt);
            }
        });
        plasnedoMenuBar.add(pedido);

        setJMenuBar(plasnedoMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(receptor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(parcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(pagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(receptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(parcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pagar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cadastrar)
                        .addComponent(editar)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pessoaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pessoaMenuMouseClicked
        dispose();
        new PessoaFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_pessoaMenuMouseClicked

    private void pessoaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaMenuActionPerformed
        dispose();
        new PessoaFrame().setVisible(true);
        
        
    }//GEN-LAST:event_pessoaMenuActionPerformed

    private void produtoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtoMenuMouseClicked
        dispose();
        new ProdutoFrame().setVisible(true);             // TODO add your handling code here:
    }//GEN-LAST:event_produtoMenuMouseClicked

    private void produtoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoMenuActionPerformed
        dispose();
        new ProdutoFrame().setVisible(true);
        
    }//GEN-LAST:event_produtoMenuActionPerformed

    private void pedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedidoMouseClicked
        dispose();
        new PedidoFrame().setVisible(true);
        
    }//GEN-LAST:event_pedidoMouseClicked

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
         ContaPagar conta = new ContaPagar();
         conta.setStatus(false);
         conta.setDescricao(descricao.getText());
        

         
        int ide = 0;
        boolean faiou = false;
        try{
            ide = Integer.parseInt(id.getText());
        }catch(Exception e){
            faiou = true;
            JOptionPane.showMessageDialog(null, "ERRO! O campo ID deve conter apenas numeros!");
        }
         conta.setIdContaPagar(ide);        
        
        

        int qParcelas = 0;
        try{
            qParcelas = Integer.parseInt(id.getText());
        }catch(Exception e){
            faiou = true;
            JOptionPane.showMessageDialog(null, "ERRO! O campo Parcelas deve conter apenas numeros!");
        }
        conta.setQtdparcelas(qParcelas);
        
        double valorr = 0;
        try{
            valorr = Double.parseDouble(id.getText());
        }catch(Exception e){
            faiou = true;
            JOptionPane.showMessageDialog(null, "ERRO! O campo valor deve conter apenas numeros e um ponto!");
        }
         conta.setValor(valorr);
         
        int idPessoa = Integer.parseInt(receptor.getText());
        Pessoa p = PessoaDAO.getPessoaId(idPessoa);
        int i = -1;
        try{
            i = p.getIdPessoa();
        }catch(Exception e){
            faiou = true;
            JOptionPane.showMessageDialog(null, "ERRO! O código de Pessoa Jurídica deve corresponder a alguma pessoa cadastrada!");
        }
        
        if(i==idPessoa){
            conta.setPessoa(idPessoa);
        }else{
            faiou = true;
            JOptionPane.showMessageDialog(null, "ERRO! O código de Pessoa Jurídica deve corresponder ao código cadastrado no endereço!");
        }


        if(!faiou){
            try {

                ContaDAO.createContaPagar(conta);
                JOptionPane.showMessageDialog(null, "Conta inserida com sucesso! ");

                id.setText("");
                receptor.setText("");
                vencimento.setText("");
                valor.setText("");
                parcelas.setText("");
                descricao.setText("");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro de inserção! Verifique os dados e tente novamente.");
            }
        }
        
        
        
    }//GEN-LAST:event_cadastrarActionPerformed

    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        try{
        ContaPagar conta = ContaDAO.getContaPagarId(Integer.parseInt(id.getText()));
        conta.setStatus(true);
        ContaDAO.updateContaPagar(conta);
        JOptionPane.showMessageDialog(null, "Conta paga com sucesso!");
        dispose();
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Erro de inserção! Verifique os dados e tente novamente.");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_pagarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        
        if(id!=null){
        

         
        int ide = 0;
        boolean faiou = false;
        try{
            ide = Integer.parseInt(id.getText());
        }catch(Exception e){
            faiou = true;
            JOptionPane.showMessageDialog(null, "ERRO! O campo ID deve conter apenas numeros!");
        }
        
        ContaPagar conta = ContaDAO.getContaPagarId(ide);
         conta.setDescricao(descricao.getText());
        
        

        int qParcelas = 0;
        try{
            qParcelas = Integer.parseInt(id.getText());
        }catch(Exception e){
            faiou = true;
            JOptionPane.showMessageDialog(null, "ERRO! O campo Parcelas deve conter apenas numeros!");
        }
        conta.setQtdparcelas(qParcelas);
        
        double valorr = 0;
        try{
            valorr = Double.parseDouble(id.getText());
        }catch(Exception e){
            faiou = true;
            JOptionPane.showMessageDialog(null, "ERRO! O campo valor deve conter apenas numeros e um ponto!");
        }
         conta.setValor(valorr);
         
        int idPessoa = Integer.parseInt(receptor.getText());
        Pessoa p = PessoaDAO.getPessoaId(idPessoa);
        int i = -1;
        try{
            i = p.getIdPessoa();
        }catch(Exception e){
            faiou = true;
            JOptionPane.showMessageDialog(null, "ERRO! O código de Pessoa Jurídica deve corresponder a alguma pessoa cadastrada!");
        }
        
        if(i==idPessoa){
            conta.setPessoa(idPessoa);
        }else{
            faiou = true;
            JOptionPane.showMessageDialog(null, "ERRO! O código de Pessoa Jurídica deve corresponder ao código cadastrado no endereço!");
        }


        if(!faiou){
            try {

                ContaDAO.updateContaPagar(conta);
                JOptionPane.showMessageDialog(null, "Conta alterada com sucesso! ");

                id.setText("");
                receptor.setText("");
                vencimento.setText("");
                valor.setText("");
                parcelas.setText("");
                descricao.setText("");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro de inserção! Verifique os dados e tente novamente.");
            }
        }
        
        }else{
            JOptionPane.showMessageDialog(null, "Erro! É preciso manter o ID!");
        }


        
    }//GEN-LAST:event_editarActionPerformed

    private void descricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaContaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaContaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaContaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaContaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaContaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField descricao;
    private javax.swing.JButton editar;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton pagar;
    private javax.swing.JTextField parcelas;
    private javax.swing.JMenu pedido;
    private javax.swing.JMenu pessoaMenu;
    private javax.swing.JMenuBar plasnedoMenuBar;
    private javax.swing.JMenu produtoMenu;
    private javax.swing.JTextField receptor;
    private javax.swing.JTextField valor;
    private javax.swing.JTextField vencimento;
    // End of variables declaration//GEN-END:variables
}
