/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;



import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import view.PessoaFrame;
import view.ProdutoFrame;


/**
 *
 * @author menegazzo
 */
public class PedidoFrame extends javax.swing.JFrame {

    /**
     * Creates new form PedidoFrame
     */
    public PedidoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pedidoAba = new javax.swing.JTabbedPane();
        buscapedidoAba = new javax.swing.JPanel();
        tabelabuscaScrollPane = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        limparbuscapedidoButton = new javax.swing.JButton();
        buscarbuscapedidoButton = new javax.swing.JButton();
        tipopedidobuscaCampo = new javax.swing.JTextField();
        tipopedidobuscaLabel = new javax.swing.JLabel();
        produtobuscapedidoLabel = new javax.swing.JLabel();
        produtobuscapedidoCampo = new javax.swing.JTextField();
        clientebuscapedidoCampo = new javax.swing.JTextField();
        clientebuscapedidoLabel = new javax.swing.JLabel();
        representantebuscapedidoLabel = new javax.swing.JLabel();
        representantebuscapedidoCampo = new javax.swing.JTextField();
        qtdebuscapedidoLabel = new javax.swing.JLabel();
        qtdebuscapedidoCampo = new javax.swing.JTextField();
        codigobuscapedidoLabel = new javax.swing.JLabel();
        codigobuscapedidoCampo = new javax.swing.JTextField();
        statusbuscapedidoLabel = new javax.swing.JLabel();
        statusbuscapedidoCampo = new javax.swing.JTextField();
        fazerpedidoAba = new javax.swing.JPanel();
        codigopedidoLabel = new javax.swing.JLabel();
        clientepedidoLabel = new javax.swing.JLabel();
        codigopedidoCampo = new javax.swing.JTextField();
        clientepedidoCampo = new javax.swing.JTextField();
        tabelapedidoScrollPane = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        adicionarpedidoButton = new javax.swing.JButton();
        removerpedidoButton = new javax.swing.JButton();
        representantepedidoLabel = new javax.swing.JLabel();
        representantepedidoCampo = new javax.swing.JTextField();
        tipopedidoLabel = new javax.swing.JLabel();
        tipopedidoCampo = new javax.swing.JTextField();
        statuspedidoLabel = new javax.swing.JLabel();
        statuspedidoComboBox = new javax.swing.JComboBox<>();
        fatorpedidoLabel = new javax.swing.JLabel();
        fatorpedidoCampo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idProdutoAdicionaCampo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        quantidadeAdicionaCampo = new javax.swing.JTextField();
        totalPedido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        plasnedoMenuBar = new javax.swing.JMenuBar();
        pessoaMenu = new javax.swing.JMenu();
        produtoMenu = new javax.swing.JMenu();
        pedido = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Representante", "Tipo de pedido", "Status"
            }
        ));
        tabelabuscaScrollPane.setViewportView(jTable3);

        limparbuscapedidoButton.setText("Limpar");

        buscarbuscapedidoButton.setText("Buscar");
        buscarbuscapedidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbuscapedidoButtonActionPerformed(evt);
            }
        });

        tipopedidobuscaCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipopedidobuscaCampoActionPerformed(evt);
            }
        });

        tipopedidobuscaLabel.setText("Tipo do pedido");

        produtobuscapedidoLabel.setText("Produto");

        clientebuscapedidoLabel.setText("Cliente");

        representantebuscapedidoLabel.setText("Representante");

        representantebuscapedidoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                representantebuscapedidoCampoActionPerformed(evt);
            }
        });

        qtdebuscapedidoLabel.setText("Qtde");

        codigobuscapedidoLabel.setText("Código");

        statusbuscapedidoLabel.setText("Status");

        javax.swing.GroupLayout buscapedidoAbaLayout = new javax.swing.GroupLayout(buscapedidoAba);
        buscapedidoAba.setLayout(buscapedidoAbaLayout);
        buscapedidoAbaLayout.setHorizontalGroup(
            buscapedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscapedidoAbaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscapedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelabuscaScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(buscapedidoAbaLayout.createSequentialGroup()
                        .addComponent(clientebuscapedidoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientebuscapedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(representantebuscapedidoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(representantebuscapedidoCampo))
                    .addGroup(buscapedidoAbaLayout.createSequentialGroup()
                        .addComponent(produtobuscapedidoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(produtobuscapedidoCampo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtdebuscapedidoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtdebuscapedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(codigobuscapedidoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigobuscapedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buscapedidoAbaLayout.createSequentialGroup()
                        .addGroup(buscapedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(buscapedidoAbaLayout.createSequentialGroup()
                                .addComponent(buscarbuscapedidoButton)
                                .addGap(18, 18, 18)
                                .addComponent(limparbuscapedidoButton)
                                .addGap(0, 127, Short.MAX_VALUE))
                            .addGroup(buscapedidoAbaLayout.createSequentialGroup()
                                .addComponent(tipopedidobuscaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipopedidobuscaCampo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusbuscapedidoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusbuscapedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(317, 317, 317)))
                .addContainerGap())
        );
        buscapedidoAbaLayout.setVerticalGroup(
            buscapedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscapedidoAbaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscapedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientebuscapedidoLabel)
                    .addComponent(clientebuscapedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(representantebuscapedidoLabel)
                    .addComponent(representantebuscapedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(buscapedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produtobuscapedidoLabel)
                    .addComponent(produtobuscapedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigobuscapedidoLabel)
                    .addComponent(codigobuscapedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtdebuscapedidoLabel)
                    .addComponent(qtdebuscapedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(buscapedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipopedidobuscaLabel)
                    .addComponent(tipopedidobuscaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusbuscapedidoLabel)
                    .addComponent(statusbuscapedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(buscapedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarbuscapedidoButton)
                    .addComponent(limparbuscapedidoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelabuscaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pedidoAba.addTab("Busca", buscapedidoAba);

        codigopedidoLabel.setText("Código");

        clientepedidoLabel.setText("Cliente");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Produto", "Valor", "Quantidade", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelapedidoScrollPane.setViewportView(jTable2);

        adicionarpedidoButton.setText("Adicionar item");
        adicionarpedidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarpedidoButtonActionPerformed(evt);
            }
        });

        removerpedidoButton.setText("Remover item");
        removerpedidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerpedidoButtonActionPerformed(evt);
            }
        });

        representantepedidoLabel.setText("Representante");

        representantepedidoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                representantepedidoCampoActionPerformed(evt);
            }
        });

        tipopedidoLabel.setText("Tipo do pedido");

        statuspedidoLabel.setText("Status");

        statuspedidoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        fatorpedidoLabel.setText("Fator");

        jLabel1.setText("____________________________________________________________________________________________________________");

        jButton1.setText("Finalizar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        jLabel2.setText("Id Produto");

        idProdutoAdicionaCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProdutoAdicionaCampoActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade");

        totalPedido.setText("0");

        jLabel5.setText("Sub TOTAL");

        javax.swing.GroupLayout fazerpedidoAbaLayout = new javax.swing.GroupLayout(fazerpedidoAba);
        fazerpedidoAba.setLayout(fazerpedidoAbaLayout);
        fazerpedidoAbaLayout.setHorizontalGroup(
            fazerpedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fazerpedidoAbaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fazerpedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fazerpedidoAbaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idProdutoAdicionaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidadeAdicionaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adicionarpedidoButton)
                        .addGap(18, 18, 18)
                        .addComponent(removerpedidoButton)
                        .addGap(117, 117, 117))
                    .addComponent(tabelapedidoScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fazerpedidoAbaLayout.createSequentialGroup()
                        .addGroup(fazerpedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fazerpedidoAbaLayout.createSequentialGroup()
                                .addComponent(clientepedidoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clientepedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(representantepedidoLabel))
                            .addGroup(fazerpedidoAbaLayout.createSequentialGroup()
                                .addComponent(tipopedidoLabel)
                                .addGap(12, 12, 12)
                                .addComponent(tipopedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(statuspedidoLabel)
                                .addGap(18, 18, 18)
                                .addComponent(statuspedidoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fatorpedidoLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fazerpedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fazerpedidoAbaLayout.createSequentialGroup()
                                .addComponent(fatorpedidoCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigopedidoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigopedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(representantepedidoCampo)))
                    .addGroup(fazerpedidoAbaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fazerpedidoAbaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(37, 37, 37)
                        .addComponent(totalPedido)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        fazerpedidoAbaLayout.setVerticalGroup(
            fazerpedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fazerpedidoAbaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fazerpedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientepedidoLabel)
                    .addComponent(clientepedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(representantepedidoLabel)
                    .addComponent(representantepedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fazerpedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipopedidoLabel)
                    .addComponent(tipopedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statuspedidoLabel)
                    .addComponent(statuspedidoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatorpedidoLabel)
                    .addComponent(fatorpedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigopedidoLabel)
                    .addComponent(codigopedidoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fazerpedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarpedidoButton)
                    .addComponent(removerpedidoButton)
                    .addComponent(jLabel2)
                    .addComponent(idProdutoAdicionaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(quantidadeAdicionaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tabelapedidoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fazerpedidoAbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(totalPedido)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7))
        );

        pedidoAba.addTab("Pedido", fazerpedidoAba);

        pessoaMenu.setText("Pessoa");
        pessoaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pessoaMenuMouseClicked(evt);
            }
        });
        pessoaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaMenuActionPerformed(evt);
            }
        });
        plasnedoMenuBar.add(pessoaMenu);

        produtoMenu.setText("Produto");
        produtoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtoMenuMouseClicked(evt);
            }
        });
        produtoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoMenuActionPerformed(evt);
            }
        });
        plasnedoMenuBar.add(produtoMenu);

        pedido.setText("Pedido");
        pedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedidoMouseClicked(evt);
            }
        });
        pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoActionPerformed(evt);
            }
        });
        plasnedoMenuBar.add(pedido);

        setJMenuBar(plasnedoMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pedidoAba)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pedidoAba)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pessoaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pessoaMenuMouseClicked
        dispose();
        new PessoaFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_pessoaMenuMouseClicked

    private void pessoaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaMenuActionPerformed
        new PessoaFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_pessoaMenuActionPerformed

    private void produtoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtoMenuMouseClicked
        dispose();
        new ProdutoFrame().setVisible(true);             // TODO add your handling code here:
    }//GEN-LAST:event_produtoMenuMouseClicked

    private void produtoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoMenuActionPerformed
        new ProdutoFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_produtoMenuActionPerformed

    private void adicionarpedidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarpedidoButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int totalLinha = (Integer.parseInt(quantidadeAdicionaCampo.getText()))*(100);
        model.addRow(new Object[]{idProdutoAdicionaCampo.getText(), 100, Integer.parseInt(quantidadeAdicionaCampo.getText()),totalLinha });
        /*int totalCompra = Integer.parseInt(totalPedido.getText());
        totalPedido.setText(Integer.toString(totalCompra + totalLinha));
        */
        int total = 0;
        for (int i = 0; i < jTable2.getRowCount(); i++){
            int amount = Integer.parseInt(jTable2.getValueAt(i, 3)+"");
            total += amount;
        }
        totalPedido.setText(Integer.toString(total));
    }//GEN-LAST:event_adicionarpedidoButtonActionPerformed

    private void buscarbuscapedidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbuscapedidoButtonActionPerformed
                           
    }//GEN-LAST:event_buscarbuscapedidoButtonActionPerformed

    private void pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoActionPerformed
        // TODO add your handling code here:
        new PedidoFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_pedidoActionPerformed

    private void pedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedidoMouseClicked
        // TODO add your handling code here:
        new PedidoFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_pedidoMouseClicked

    private void representantepedidoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_representantepedidoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_representantepedidoCampoActionPerformed

    private void representantebuscapedidoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_representantebuscapedidoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_representantebuscapedidoCampoActionPerformed

    private void tipopedidobuscaCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipopedidobuscaCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipopedidobuscaCampoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idProdutoAdicionaCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProdutoAdicionaCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProdutoAdicionaCampoActionPerformed

    private void removerpedidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerpedidoButtonActionPerformed
        removeSelectedRows(jTable2);
    }//GEN-LAST:event_removerpedidoButtonActionPerformed
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoFrame().setVisible(true);
            }
        });
    }
    public void removeSelectedRows(JTable table){
        DefaultTableModel model = (DefaultTableModel) this.jTable2.getModel();
        int[] rows = table.getSelectedRows();
        for(int i=0;i<rows.length;i++){
            model.removeRow(rows[i]-i);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarpedidoButton;
    private javax.swing.JPanel buscapedidoAba;
    private javax.swing.JButton buscarbuscapedidoButton;
    private javax.swing.JTextField clientebuscapedidoCampo;
    private javax.swing.JLabel clientebuscapedidoLabel;
    private javax.swing.JTextField clientepedidoCampo;
    private javax.swing.JLabel clientepedidoLabel;
    private javax.swing.JTextField codigobuscapedidoCampo;
    private javax.swing.JLabel codigobuscapedidoLabel;
    private javax.swing.JTextField codigopedidoCampo;
    private javax.swing.JLabel codigopedidoLabel;
    private javax.swing.JTextField fatorpedidoCampo;
    private javax.swing.JLabel fatorpedidoLabel;
    private javax.swing.JPanel fazerpedidoAba;
    private javax.swing.JTextField idProdutoAdicionaCampo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton limparbuscapedidoButton;
    private javax.swing.JMenu pedido;
    private javax.swing.JTabbedPane pedidoAba;
    private javax.swing.JMenu pessoaMenu;
    private javax.swing.JMenuBar plasnedoMenuBar;
    private javax.swing.JMenu produtoMenu;
    private javax.swing.JTextField produtobuscapedidoCampo;
    private javax.swing.JLabel produtobuscapedidoLabel;
    private javax.swing.JTextField qtdebuscapedidoCampo;
    private javax.swing.JLabel qtdebuscapedidoLabel;
    private javax.swing.JTextField quantidadeAdicionaCampo;
    private javax.swing.JButton removerpedidoButton;
    private javax.swing.JTextField representantebuscapedidoCampo;
    private javax.swing.JLabel representantebuscapedidoLabel;
    private javax.swing.JTextField representantepedidoCampo;
    private javax.swing.JLabel representantepedidoLabel;
    private javax.swing.JTextField statusbuscapedidoCampo;
    private javax.swing.JLabel statusbuscapedidoLabel;
    private javax.swing.JComboBox<String> statuspedidoComboBox;
    private javax.swing.JLabel statuspedidoLabel;
    private javax.swing.JScrollPane tabelabuscaScrollPane;
    private javax.swing.JScrollPane tabelapedidoScrollPane;
    private javax.swing.JTextField tipopedidoCampo;
    private javax.swing.JLabel tipopedidoLabel;
    private javax.swing.JTextField tipopedidobuscaCampo;
    private javax.swing.JLabel tipopedidobuscaLabel;
    private javax.swing.JLabel totalPedido;
    // End of variables declaration//GEN-END:variables
}
