/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.InformacoesBancarias;
import model.Pessoa;
import control.PessoaControl;
import dao.PessoaDAO;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pauloapanucci
 */
public class PessoaFrame extends javax.swing.JFrame {

    /**
     * Creates new form PessoaFisicaFrame
     */
    public PessoaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField14 = new javax.swing.JTextField();
        pjtipobuttonGroup = new javax.swing.ButtonGroup();
        dadospjAba2 = new javax.swing.JTabbedPane();
        pessoaispjAba1 = new javax.swing.JPanel();
        pjcodigoLabel1 = new javax.swing.JLabel();
        pjcodigoCampo1 = new javax.swing.JTextField();
        pjabaenderecoButton1 = new javax.swing.JButton();
        pjbuscaScrollPane1 = new javax.swing.JScrollPane();
        pessoaJuridicaTabela1 = new javax.swing.JTable();
        buscarpjButton1 = new javax.swing.JButton();
        pjlimparButton1 = new javax.swing.JButton();
        enderecopjAba2 = new javax.swing.JPanel();
        pjenderecoLabel2 = new javax.swing.JLabel();
        pjenderecoCampo2 = new javax.swing.JTextField();
        pjcomplementoLabel2 = new javax.swing.JLabel();
        pjcomplementoCampo2 = new javax.swing.JTextField();
        pjnumeroLabel2 = new javax.swing.JLabel();
        pjnumeroCampo2 = new javax.swing.JTextField();
        pjcepLabel2 = new javax.swing.JLabel();
        pjcepCampo2 = new javax.swing.JTextField();
        pjcaixapostalLabel2 = new javax.swing.JLabel();
        pjcaixapostalCampo2 = new javax.swing.JTextField();
        pjbairroLabel2 = new javax.swing.JLabel();
        pjbairroCampo2 = new javax.swing.JTextField();
        pjcidadeLabel2 = new javax.swing.JLabel();
        pjcidadeCampo2 = new javax.swing.JTextField();
        pjestadoLabel2 = new javax.swing.JLabel();
        pjEstadosComboBox3 = new javax.swing.JComboBox<>();
        pjtelefone1Label2 = new javax.swing.JLabel();
        pjtelefone1Campo2 = new javax.swing.JTextField();
        pjemailLabel2 = new javax.swing.JLabel();
        pjemailCampo2 = new javax.swing.JTextField();
        pjtelefone2Label2 = new javax.swing.JLabel();
        pjtelefone2Campo2 = new javax.swing.JTextField();
        pjababancariosButton9 = new javax.swing.JButton();
        pjabapessoaisButton2 = new javax.swing.JButton();
        bancariospjAba1 = new javax.swing.JPanel();
        pjidcontaCampo1 = new javax.swing.JTextField();
        pjbancoCampo1 = new javax.swing.JTextField();
        pjagenciaCampo1 = new javax.swing.JTextField();
        pjcontacorrenteCampo1 = new javax.swing.JTextField();
        pjtitularCampo1 = new javax.swing.JTextField();
        pjidcontaLabel1 = new javax.swing.JLabel();
        pjcnpjtitularCampo1 = new javax.swing.JTextField();
        pjbancoLabel1 = new javax.swing.JLabel();
        pjagenciaLabel1 = new javax.swing.JLabel();
        pjcontacorrenteLabel1 = new javax.swing.JLabel();
        pjtitularLabel1 = new javax.swing.JLabel();
        pjcnpjtitularLabel1 = new javax.swing.JLabel();
        pjcpftitularLabel1 = new javax.swing.JLabel();
        pjcpftitularCampo1 = new javax.swing.JTextField();
        pjremoverButton6 = new javax.swing.JButton();
        pjalterarButton6 = new javax.swing.JButton();
        pjabaenderecoButton3 = new javax.swing.JButton();
        pjincluirButton1 = new javax.swing.JButton();
        plasnedoMenuBar = new javax.swing.JMenuBar();
        pessoaMenu = new javax.swing.JMenu();

        jTextField14.setText("jTextField14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pjcodigoLabel1.setText("Código");

        pjcodigoCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjcodigoCampo1ActionPerformed(evt);
            }
        });

        pjabaenderecoButton1.setText("Próximo");
        pjabaenderecoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjabaenderecoButton1ActionPerformed(evt);
            }
        });

        pessoaJuridicaTabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CNPJ", "Inscrição Estadual", "Razão Social", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pessoaJuridicaTabela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pessoaJuridicaTabela1MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pessoaJuridicaTabela1MouseClicked(evt);
            }
        });
        pjbuscaScrollPane1.setViewportView(pessoaJuridicaTabela1);

        buscarpjButton1.setText("Buscar");
        buscarpjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpjButton1ActionPerformed(evt);
            }
        });

        pjlimparButton1.setText("Limpar");
        pjlimparButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjlimparButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pessoaispjAba1Layout = new javax.swing.GroupLayout(pessoaispjAba1);
        pessoaispjAba1.setLayout(pessoaispjAba1Layout);
        pessoaispjAba1Layout.setHorizontalGroup(
            pessoaispjAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pjbuscaScrollPane1)
            .addGroup(pessoaispjAba1Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addGroup(pessoaispjAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pjcodigoLabel1)
                    .addComponent(buscarpjButton1))
                .addGap(34, 34, 34)
                .addGroup(pessoaispjAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pjlimparButton1)
                    .addComponent(pjcodigoCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(pjabaenderecoButton1)
                .addContainerGap())
        );
        pessoaispjAba1Layout.setVerticalGroup(
            pessoaispjAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pessoaispjAba1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pessoaispjAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pjcodigoLabel1)
                    .addComponent(pjcodigoCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pjabaenderecoButton1))
                .addGap(18, 18, 18)
                .addGroup(pessoaispjAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarpjButton1)
                    .addComponent(pjlimparButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(pjbuscaScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dadospjAba2.addTab("Dados pessoais", pessoaispjAba1);

        pjenderecoLabel2.setText("Endereço");

        pjenderecoCampo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjenderecoCampo2pjenderecoCampoActionPerformed(evt);
            }
        });

        pjcomplementoLabel2.setText("Complemento");

        pjnumeroLabel2.setText("Número");

        pjcepLabel2.setText("CEP");

        pjcaixapostalLabel2.setText("Caixa postal");

        pjbairroLabel2.setText("Bairro");

        pjcidadeLabel2.setText("Cidade");

        pjestadoLabel2.setText("Estado");

        pjEstadosComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "MP", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));

        pjtelefone1Label2.setText("Telefone");

        pjemailLabel2.setText("E-mail");

        pjtelefone2Label2.setText("Telefone");

        pjababancariosButton9.setText("Próximo");
        pjababancariosButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjababancariosButton9pjababancariosButton7ActionPerformed(evt);
            }
        });

        pjabapessoaisButton2.setText("Anterior");
        pjabapessoaisButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjabapessoaisButton2pjabapessoaisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enderecopjAba2Layout = new javax.swing.GroupLayout(enderecopjAba2);
        enderecopjAba2.setLayout(enderecopjAba2Layout);
        enderecopjAba2Layout.setHorizontalGroup(
            enderecopjAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecopjAba2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enderecopjAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enderecopjAba2Layout.createSequentialGroup()
                        .addComponent(pjbairroLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(pjbairroCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pjcidadeLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pjcidadeCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pjestadoLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(pjEstadosComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enderecopjAba2Layout.createSequentialGroup()
                        .addGroup(enderecopjAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(enderecopjAba2Layout.createSequentialGroup()
                                .addComponent(pjtelefone1Label2)
                                .addGap(18, 18, 18)
                                .addComponent(pjtelefone1Campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pjtelefone2Label2)
                                .addGap(18, 18, 18)
                                .addComponent(pjtelefone2Campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(enderecopjAba2Layout.createSequentialGroup()
                                .addComponent(pjabapessoaisButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pjababancariosButton9)))
                        .addGap(18, 18, 18)
                        .addComponent(pjemailLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(pjemailCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enderecopjAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, enderecopjAba2Layout.createSequentialGroup()
                            .addComponent(pjnumeroLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(pjnumeroCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pjcepLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(pjcepCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pjcaixapostalLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(pjcaixapostalCampo2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, enderecopjAba2Layout.createSequentialGroup()
                            .addComponent(pjenderecoLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(pjenderecoCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pjcomplementoLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(pjcomplementoCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        enderecopjAba2Layout.setVerticalGroup(
            enderecopjAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecopjAba2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enderecopjAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pjenderecoCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pjenderecoLabel2)
                    .addComponent(pjcomplementoLabel2)
                    .addComponent(pjcomplementoCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(enderecopjAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pjnumeroLabel2)
                    .addComponent(pjnumeroCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pjcepLabel2)
                    .addComponent(pjcepCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pjcaixapostalLabel2)
                    .addComponent(pjcaixapostalCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(enderecopjAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pjbairroLabel2)
                    .addComponent(pjbairroCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pjcidadeLabel2)
                    .addComponent(pjcidadeCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pjestadoLabel2)
                    .addComponent(pjEstadosComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(enderecopjAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pjtelefone1Label2)
                    .addComponent(pjtelefone1Campo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pjtelefone2Label2)
                    .addComponent(pjtelefone2Campo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pjemailLabel2)
                    .addComponent(pjemailCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecopjAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pjababancariosButton9)
                    .addComponent(pjabapessoaisButton2))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        dadospjAba2.addTab("Endereço", enderecopjAba2);

        pjbancoCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjbancoCampo1ActionPerformed(evt);
            }
        });

        pjagenciaCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjagenciaCampo1ActionPerformed(evt);
            }
        });

        pjidcontaLabel1.setText("Código da conta");

        pjbancoLabel1.setText("Banco");

        pjagenciaLabel1.setText("Agencia");

        pjcontacorrenteLabel1.setText("Conta corrente");

        pjtitularLabel1.setText("Titular");

        pjcnpjtitularLabel1.setText("CNPJ");

        pjcpftitularLabel1.setText("CPF");

        pjremoverButton6.setText("Remover");
        pjremoverButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjremoverButton6ActionPerformed(evt);
            }
        });

        pjalterarButton6.setText("Alterar");
        pjalterarButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pjalterarButton6MouseClicked(evt);
            }
        });
        pjalterarButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjalterarButton6ActionPerformed(evt);
            }
        });

        pjabaenderecoButton3.setText("Anterior");
        pjabaenderecoButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjabaenderecoButton3ActionPerformed(evt);
            }
        });

        pjincluirButton1.setText("Incluir");
        pjincluirButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjincluirButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bancariospjAba1Layout = new javax.swing.GroupLayout(bancariospjAba1);
        bancariospjAba1.setLayout(bancariospjAba1Layout);
        bancariospjAba1Layout.setHorizontalGroup(
            bancariospjAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bancariospjAba1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bancariospjAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bancariospjAba1Layout.createSequentialGroup()
                        .addComponent(pjidcontaLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pjidcontaCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pjbancoLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(pjbancoCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pjagenciaLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(pjagenciaCampo1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                    .addGroup(bancariospjAba1Layout.createSequentialGroup()
                        .addComponent(pjcontacorrenteLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(pjcontacorrenteCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pjtitularLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(pjtitularCampo1))
                    .addGroup(bancariospjAba1Layout.createSequentialGroup()
                        .addComponent(pjcnpjtitularLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(pjcnpjtitularCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pjcpftitularLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(pjcpftitularCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(bancariospjAba1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(pjabaenderecoButton3)
                .addGap(18, 18, 18)
                .addComponent(pjincluirButton1)
                .addGap(18, 18, 18)
                .addComponent(pjalterarButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pjremoverButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bancariospjAba1Layout.setVerticalGroup(
            bancariospjAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bancariospjAba1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bancariospjAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pjidcontaLabel1)
                    .addComponent(pjbancoLabel1)
                    .addComponent(pjbancoCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pjagenciaLabel1)
                    .addComponent(pjagenciaCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pjidcontaCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bancariospjAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pjcontacorrenteLabel1)
                    .addComponent(pjcontacorrenteCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pjtitularLabel1)
                    .addComponent(pjtitularCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bancariospjAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pjcnpjtitularLabel1)
                    .addComponent(pjcnpjtitularCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pjcpftitularLabel1)
                    .addComponent(pjcpftitularCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bancariospjAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pjabaenderecoButton3)
                    .addComponent(pjincluirButton1)
                    .addComponent(pjalterarButton6)
                    .addComponent(pjremoverButton6))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        dadospjAba2.addTab("Dados bancários", bancariospjAba1);

        pessoaMenu.setText("Pessoa");
        pessoaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pessoaMenuMouseClicked(evt);
            }
        });
        pessoaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaMenuActionPerformed(evt);
            }
        });
        plasnedoMenuBar.add(pessoaMenu);

        setJMenuBar(plasnedoMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dadospjAba2, javax.swing.GroupLayout.PREFERRED_SIZE, 1128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dadospjAba2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pessoaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pessoaMenuMouseClicked
        dispose();
        new PessoaFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_pessoaMenuMouseClicked

    private void pessoaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaMenuActionPerformed
        new PessoaFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_pessoaMenuActionPerformed

    private void pjincluirButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjincluirButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjincluirButton1ActionPerformed

    private void pjabaenderecoButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjabaenderecoButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjabaenderecoButton3ActionPerformed

    private void pjalterarButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjalterarButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjalterarButton6ActionPerformed

    private void pjalterarButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pjalterarButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pjalterarButton6MouseClicked

    private void pjremoverButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjremoverButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjremoverButton6ActionPerformed

    private void pjagenciaCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjagenciaCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjagenciaCampo1ActionPerformed

    private void pjbancoCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjbancoCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjbancoCampo1ActionPerformed

    private void pjabapessoaisButton2pjabapessoaisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjabapessoaisButton2pjabapessoaisButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjabapessoaisButton2pjabapessoaisButtonActionPerformed

    private void pjababancariosButton9pjababancariosButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjababancariosButton9pjababancariosButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjababancariosButton9pjababancariosButton7ActionPerformed

    private void pjenderecoCampo2pjenderecoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjenderecoCampo2pjenderecoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjenderecoCampo2pjenderecoCampoActionPerformed

    private void pjlimparButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjlimparButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjlimparButton1ActionPerformed

    private void buscarpjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpjButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarpjButton1ActionPerformed

    private void pessoaJuridicaTabela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pessoaJuridicaTabela1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pessoaJuridicaTabela1MouseClicked

    private void pessoaJuridicaTabela1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pessoaJuridicaTabela1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pessoaJuridicaTabela1MousePressed

    private void pjabaenderecoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjabaenderecoButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjabaenderecoButton1ActionPerformed

    private void pjcodigoCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjcodigoCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjcodigoCampo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bancariospjAba1;
    private javax.swing.JButton buscarpjButton1;
    private javax.swing.JTabbedPane dadospjAba;
    private javax.swing.JTabbedPane dadospjAba2;
    private javax.swing.JPanel enderecopjAba;
    private javax.swing.JPanel enderecopjAba2;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTable pessoaJuridicaTabela1;
    private javax.swing.JMenu pessoaMenu;
    private javax.swing.JPanel pessoaispjAba1;
    private javax.swing.JComboBox<String> pjEstadosComboBox1;
    private javax.swing.JComboBox<String> pjEstadosComboBox3;
    private javax.swing.JButton pjababancariosButton7;
    private javax.swing.JButton pjababancariosButton9;
    private javax.swing.JButton pjabaenderecoButton1;
    private javax.swing.JButton pjabaenderecoButton3;
    private javax.swing.JButton pjabapessoaisButton;
    private javax.swing.JButton pjabapessoaisButton2;
    private javax.swing.JTextField pjagenciaCampo1;
    private javax.swing.JLabel pjagenciaLabel1;
    private javax.swing.JButton pjalterarButton6;
    private javax.swing.JTextField pjbairroCampo;
    private javax.swing.JTextField pjbairroCampo2;
    private javax.swing.JLabel pjbairroLabel;
    private javax.swing.JLabel pjbairroLabel2;
    private javax.swing.JTextField pjbancoCampo1;
    private javax.swing.JLabel pjbancoLabel1;
    private javax.swing.JScrollPane pjbuscaScrollPane1;
    private javax.swing.JTextField pjcaixapostalCampo;
    private javax.swing.JTextField pjcaixapostalCampo2;
    private javax.swing.JLabel pjcaixapostalLabel;
    private javax.swing.JLabel pjcaixapostalLabel2;
    private javax.swing.JTextField pjcepCampo;
    private javax.swing.JTextField pjcepCampo2;
    private javax.swing.JLabel pjcepLabel;
    private javax.swing.JLabel pjcepLabel2;
    private javax.swing.JTextField pjcidadeCampo;
    private javax.swing.JTextField pjcidadeCampo2;
    private javax.swing.JLabel pjcidadeLabel;
    private javax.swing.JLabel pjcidadeLabel2;
    private javax.swing.JTextField pjcnpjtitularCampo1;
    private javax.swing.JLabel pjcnpjtitularLabel1;
    private javax.swing.JTextField pjcodigoCampo1;
    private javax.swing.JLabel pjcodigoLabel1;
    private javax.swing.JTextField pjcomplementoCampo;
    private javax.swing.JTextField pjcomplementoCampo2;
    private javax.swing.JLabel pjcomplementoLabel;
    private javax.swing.JLabel pjcomplementoLabel2;
    private javax.swing.JTextField pjcontacorrenteCampo1;
    private javax.swing.JLabel pjcontacorrenteLabel1;
    private javax.swing.JTextField pjcpftitularCampo1;
    private javax.swing.JLabel pjcpftitularLabel1;
    private javax.swing.JTextField pjemailCampo;
    private javax.swing.JTextField pjemailCampo2;
    private javax.swing.JLabel pjemailLabel;
    private javax.swing.JLabel pjemailLabel2;
    private javax.swing.JTextField pjenderecoCampo;
    private javax.swing.JTextField pjenderecoCampo2;
    private javax.swing.JLabel pjenderecoLabel;
    private javax.swing.JLabel pjenderecoLabel2;
    private javax.swing.JLabel pjestadoLabel;
    private javax.swing.JLabel pjestadoLabel2;
    private javax.swing.JTextField pjidcontaCampo1;
    private javax.swing.JLabel pjidcontaLabel1;
    private javax.swing.JButton pjincluirButton1;
    private javax.swing.JButton pjlimparButton1;
    private javax.swing.JTextField pjnumeroCampo;
    private javax.swing.JTextField pjnumeroCampo2;
    private javax.swing.JLabel pjnumeroLabel;
    private javax.swing.JLabel pjnumeroLabel2;
    private javax.swing.JButton pjremoverButton6;
    private javax.swing.JTextField pjtelefone1Campo;
    private javax.swing.JTextField pjtelefone1Campo2;
    private javax.swing.JLabel pjtelefone1Label;
    private javax.swing.JLabel pjtelefone1Label2;
    private javax.swing.JTextField pjtelefone2Campo;
    private javax.swing.JTextField pjtelefone2Campo2;
    private javax.swing.JLabel pjtelefone2Label;
    private javax.swing.JLabel pjtelefone2Label2;
    private javax.swing.ButtonGroup pjtipobuttonGroup;
    private javax.swing.JTextField pjtitularCampo1;
    private javax.swing.JLabel pjtitularLabel1;
    private javax.swing.JMenuBar plasnedoMenuBar;
    // End of variables declaration//GEN-END:variables
}
